ALTER TABLE EVENT3_4102 ADD NBR_CELL_ID AS int null;
ALTER TABLE EVENT3_4102 ADD NBR_RNC_ID AS int null;
ALTER TABLE EVENT3_4102 ADD NBR_LAC_ID AS int null;
ALTER TABLE EVENT3_4102 ADD NBR_MCC_ID AS VARCHAR  NULL ;
ALTER TABLE EVENT3_4102 ADD NBR_MNC_ID AS VARCHAR  NULL ;