Update EVENT_4097 set pmRrcConnEstabFailCause3 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=3 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause4 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=4 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID ;
Update EVENT_4097 set pmRrcConnEstabFailCause7 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=7 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause8 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=8 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause9 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=9 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID ;
Update EVENT_4097 set pmRrcConnEstabFailCause10 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=10 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause11 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=11 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID ;
Update EVENT_4097 set pmRrcConnEstabFailCause12 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=12 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause13 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=13 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause14 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=14 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause15 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=15 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause16 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=16 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause17 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=17 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause18 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=18 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause19 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=19 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause20 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=20 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause21 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=21 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause22 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=22 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause23 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=23 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabFailCause24 = ((case when ((RRCRESULT != 0 and RRCRESULT != 2) and RRCRESULT != 1) and RRCRESULT != 5 and RRCRESULT=24 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabTimeDistrEm =1 from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 0;  
Update EVENT_4097 set pmRrcConnEstabFailFailureInRadioProcedure = ((case when RRCRESULT = 2 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID ;
Update EVENT_4097 set pmRrcConnEstabFailUnspecified = ((case when RRCRESULT = 1 then 1 else 0 end)) from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;
Update EVENT_4097 set pmRrcConnEstabTimeDistrHpa =1  from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 1 ;
Update EVENT_4097 set pmRrcConnEstabTimeDistrMod = 1 from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 4 ;
Update EVENT_4097 set pmRrcConnEstabTimeDistrMos = 1 from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 3 ;
Update EVENT_4097 set pmRrcConnEstabTimeDistrMta =1  from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where  RRCRESULT = 0 and RRCESTABLCAUSE = 2 ;
Update EVENT_4097 set pmRrcConnEstabTimeMaxEm =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 0;
Update EVENT_4097 set pmRrcConnEstabTimeMaxHpa =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 1;
Update EVENT_4097 set pmRrcConnEstabTimeMaxMod =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 4;
Update EVENT_4097 set pmRrcConnEstabTimeMaxMos =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 3;
Update EVENT_4097 set pmRrcConnEstabTimeMaxMta =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 2;
Update EVENT_4097 set pmRrcConnEstabTimeSumEm =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 0;
Update EVENT_4097 set pmRrcConnEstabTimeSumHpa =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 1;
Update EVENT_4097 set pmRrcConnEstabTimeSumMod =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 4;
Update EVENT_4097 set pmRrcConnEstabTimeSumMos =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 3;
Update EVENT_4097 set pmRrcConnEstabTimeSumMta =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4097 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where RRCRESULT = 0 and RRCESTABLCAUSE = 2;