UPDATE EVENT_4102 SET pmHoPrepAttLteInterFQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND HOPREPQCI != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND HOPREPQCI_1 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND HOPREPQCI_2 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND HOPREPQCI_3 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND HOPREPQCI_4 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND HOPREPQCI_5 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND HOPREPQCI_6 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND HOPREPQCI_7 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND HOPREPQCI_8 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND HOPREPQCI_9 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND HOPREPQCI_10 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND HOPREPQCI_11 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND HOPREPQCI_12 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND HOPREPQCI_13 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND HOPREPQCI_14 != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND HOPREPQCI_15 != NULL THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE HOSOURCEORTARGETTYPE = 1;

UPDATE EVENT_4102 SET pmHoPrepAttLteIntraFQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND HOPREPQCI != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND HOPREPQCI_1 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND HOPREPQCI_2 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND HOPREPQCI_3 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND HOPREPQCI_4 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND HOPREPQCI_5 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND HOPREPQCI_6 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND HOPREPQCI_7 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND HOPREPQCI_8 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND HOPREPQCI_9 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND HOPREPQCI_10 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND HOPREPQCI_11 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND HOPREPQCI_12 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND HOPREPQCI_13 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND HOPREPQCI_14 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND HOPREPQCI_15 != NULL   THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE HOSOURCEORTARGETTYPE = 0;

 UPDATE EVENT_4102 SET pmHoPrepOutAttQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND HOPREPQCI != NULL        THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND HOPREPQCI_1 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND HOPREPQCI_2 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND HOPREPQCI_3 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND HOPREPQCI_4 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND HOPREPQCI_5 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND HOPREPQCI_6 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND HOPREPQCI_7 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND HOPREPQCI_8 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND HOPREPQCI_9 != NULL      THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND HOPREPQCI_10 != NULL     THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND HOPREPQCI_11 != NULL     THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND HOPREPQCI_12 != NULL     THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND HOPREPQCI_13 != NULL     THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND HOPREPQCI_14 != NULL     THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND HOPREPQCI_15 != NULL     THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;

UPDATE EVENT_4102 SET pmHoPrepOutSuccQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND (HOOUTPREPERABFAILBITMAP & 1 )=0 				 AND HOPREPQCI !=NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND (HOOUTPREPERABFAILBITMAP & 2 )  /power(2,1)  	 =0  AND HOPREPQCI_1 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND (HOOUTPREPERABFAILBITMAP & 4 )  /power(2,2)  	 =0	 AND HOPREPQCI_2 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND (HOOUTPREPERABFAILBITMAP & 8 )  /power(2,3)  	 =0	 AND HOPREPQCI_3 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND (HOOUTPREPERABFAILBITMAP & 16 ) /power(2,4) 	 =0	 AND HOPREPQCI_4 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND (HOOUTPREPERABFAILBITMAP & 32 ) /power(2,5) 	 =0	 AND HOPREPQCI_5 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND (HOOUTPREPERABFAILBITMAP & 64 ) /power(2,6) 	 =0  AND HOPREPQCI_6 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND (HOOUTPREPERABFAILBITMAP & 128 ) /power(2,7)   =0	 AND HOPREPQCI_7 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND (HOOUTPREPERABFAILBITMAP & 256 ) /power(2,8)   =0	 AND HOPREPQCI_8 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND (HOOUTPREPERABFAILBITMAP & 512 ) /power(2,9)   =0	 AND HOPREPQCI_9 !=NULL  THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND (HOOUTPREPERABFAILBITMAP & 1024 ) /power(2,10)  =0	 AND HOPREPQCI_10 !=NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND (HOOUTPREPERABFAILBITMAP & 2048 ) /power(2,11)  =0	 AND HOPREPQCI_11 !=NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND (HOOUTPREPERABFAILBITMAP & 4096 ) /power(2,12)  =0	 AND HOPREPQCI_12 !=NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND (HOOUTPREPERABFAILBITMAP & 8192 ) /power(2,13)  =0	 AND HOPREPQCI_13 !=NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND (HOOUTPREPERABFAILBITMAP & 16384 ) /power(2,14) =0	 AND HOPREPQCI_14 !=NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND (HOOUTPREPERABFAILBITMAP & 32768 ) /power(2,15) =0	 AND HOPREPQCI_15 !=NULL THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID;

UPDATE EVENT_4102 SET pmHoPrepSuccLteInterFQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND HOPREPQCI != NULL THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND HOPREPQCI_1 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND HOPREPQCI_2 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND HOPREPQCI_3 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND HOPREPQCI_4 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND HOPREPQCI_5 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND HOPREPQCI_6 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND HOPREPQCI_7 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND HOPREPQCI_8 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND HOPREPQCI_9 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND HOPREPQCI_10 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND HOPREPQCI_11 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND HOPREPQCI_12 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND HOPREPQCI_13 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND HOPREPQCI_14 != NULL   THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND HOPREPQCI_15 != NULL   THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE PROCHOPREPOUTRESULT = 0 AND HOSOURCEORTARGETTYPE =1 ;

UPDATE EVENT_4102 SET pmHoPrepSuccLteIntraFQci = (
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1 ) = 1  					AND HOPREPQCI != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2 ) /power(2,1) = 1  		AND HOPREPQCI_1 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4 ) /power(2,2) = 1 		AND HOPREPQCI_2 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8 ) /power(2,3) = 1 		AND HOPREPQCI_3 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16) /power(2,4) = 1 		AND HOPREPQCI_4 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32) /power(2,5) = 1 		AND HOPREPQCI_5 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 64) /power(2,6) = 1 		AND HOPREPQCI_6 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 128) /power(2,7) = 1 		AND HOPREPQCI_7 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 256 ) /power(2,8) = 1  	AND HOPREPQCI_8 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 512 ) /power(2,9) = 1 	AND HOPREPQCI_9 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 1024 ) /power(2,10) = 1 	AND HOPREPQCI_10 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 2048 ) /power(2,11) = 1   AND HOPREPQCI_11 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 4096) /power(2,12) = 1  	AND HOPREPQCI_12 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 8192) /power(2,13) = 1 	AND HOPREPQCI_13 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 16384) /power(2,14) = 1 	AND HOPREPQCI_14 != NULL    THEN 1 ELSE 0 END) +
 (CASE WHEN (HOOUTPREPERABREQBITMAP & 32768) /power(2,15) = 1 	AND HOPREPQCI_15 != NULL    THEN 1 ELSE 0 END) 
 ) from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE PROCHOPREPOUTRESULT = 0 AND HOSOURCEORTARGETTYPE = 0 ;

 Update EVENT_4102 set pmHoPrepOutFailTo=1 from EVENT_4102 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOPREPOUTRESULT = 2 ; 