Update EVENT_4104 set pmCellHoExeAttLteInterFNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOSOURCEORTARGETTYPE = 9 and NEIGHBORPCI >= 0 AND  NEIGHBORPCI < 504;
Update EVENT_4104 set pmCellHoExeAttLteIntraFNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID  where HOSOURCEORTARGETTYPE = 8 and NEIGHBORPCI >= 0 AND  NEIGHBORPCI < 504;
Update EVENT_4104 set pmCellHoExeAttLteNpPCIQci1Ag = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where (HOSOURCEORTARGETTYPE = 8 OR HOSOURCEORTARGETTYPE = 9) AND CGIMEASMETHODTYPE = 1 AND STARTCGIMEASQCI1 = 1;
Update EVENT_4104 set pmCellHoExeAttLteNpPCIQci1Drx = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where (HOSOURCEORTARGETTYPE = 8 OR HOSOURCEORTARGETTYPE = 9) AND CGIMEASMETHODTYPE = 0 AND STARTCGIMEASQCI1 = 1;
Update EVENT_4104 set pmCellHoExeSuccLteInterFNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0 and HOSOURCEORTARGETTYPE = 9 and NEIGHBORPCI >= 0 AND  NEIGHBORPCI < 504;
Update EVENT_4104 set pmCellHoExeSuccLteIntraFNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0 and HOSOURCEORTARGETTYPE = 8 and NEIGHBORPCI >= 0 AND  NEIGHBORPCI < 504;
Update EVENT_4104 set pmCellHoExeSuccLteNpPCIQci1Ag = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0 AND (HOSOURCEORTARGETTYPE = 8 OR HOSOURCEORTARGETTYPE = 9) 	AND CGIMEASMETHODTYPE = 1 AND STARTCGIMEASQCI1 = 1;
Update EVENT_4104 set pmCellHoExeSuccLteNpPCIQci1Drx = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0 AND (HOSOURCEORTARGETTYPE = 8 OR HOSOURCEORTARGETTYPE = 9) AND CGIMEASMETHODTYPE = 0 AND STARTCGIMEASQCI1 = 1;
Update EVENT_4104 set pmHoExeAttAto = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOSOURCEORTARGETTYPE = 2 and PROCHOEXECOUTATTEMPTCAUSE = 18;
Update EVENT_4104 set pmHoExeAttBlindWcdma = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 0 and HOSOURCEORTARGETTYPE = 2;
Update EVENT_4104 set pmHoExeAttMeasBasedInterFreqNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 9;
Update EVENT_4104 set pmHoExeAttMeasBasedIntraFreqNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 8;
Update EVENT_4104 set pmHoExeAttMeasBasedWcdma = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 2;
Update EVENT_4104 set pmHoExeAttSrvccAto = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where ( (HOSOURCEORTARGETTYPE = 2 and PROCHOEXECOUTATTEMPTCAUSE = 18 ) and (SRVCCTYPE = 1 OR SRVCCTYPE = 2 ) );
Update EVENT_4104 set pmHoExeAttSrvccUeMeas = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where ((HOSOURCEORTARGETTYPE = 2 OR HOSOURCEORTARGETTYPE = 5) and SRVCCTYPE != 0 AND PROCHOEXECOUTATTEMPTCAUSE = 5 );
Update EVENT_4104 set pmHoExeAttSrvccUeMeasRsrp = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where ((HOSOURCEORTARGETTYPE = 2 OR HOSOURCEORTARGETTYPE = 5) and SRVCCTYPE != 0 AND PROCHOEXECOUTATTEMPTCAUSE = 5 AND TRIGGERQUANTITY = 0);
Update EVENT_4104 set pmHoExecOutS1AttInterEnb = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOSOURCEORTARGETTYPE = 0 or HOSOURCEORTARGETTYPE = 1;
Update EVENT_4104 set pmHoExecOutS1SuccInterEnb = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where (HOSOURCEORTARGETTYPE = 1 or HOSOURCEORTARGETTYPE = 0) and PROCHOEXECOUTRESULT = 0;
Update EVENT_4104 set pmHoExeSuccAto = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID  where HOSOURCEORTARGETTYPE = 2 and PROCHOEXECOUTRESULT = 0 and PROCHOEXECOUTATTEMPTCAUSE = 18;
Update EVENT_4104 set pmHoExeSuccBlindWcdma = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 0 and HOSOURCEORTARGETTYPE = 2 and PROCHOEXECOUTRESULT = 0;
Update EVENT_4104 set pmHoExeSuccMeasBasedInterFreqNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 9 and PROCHOEXECOUTRESULT = 0 ;
Update EVENT_4104 set pmHoExeSuccMeasBasedIntraFreqNpPCI = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 8 and PROCHOEXECOUTRESULT = 0 ;
Update EVENT_4104 set pmHoExeSuccMeasBasedWcdma = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where HOTARGETSELECTIONTYPE = 1 and HOSOURCEORTARGETTYPE = 2 and PROCHOEXECOUTRESULT = 0 ;
Update EVENT_4104 set pmHoExeSuccSrvccAto = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where (HOSOURCEORTARGETTYPE =2 and  PROCHOEXECOUTRESULT =0 and PROCHOEXECOUTATTEMPTCAUSE = 18 and (SRVCCTYPE = 1 OR SRVCCTYPE =2 ) );
Update EVENT_4104 set pmHoExeSuccSrvccUeMeas = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT =0 and PROCHOEXECOUTATTEMPTCAUSE = 5 and SRVCCTYPE != 0 and (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
Update EVENT_4104 set pmHoExeSuccSrvccUeMeasRsrp = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT =0 and PROCHOEXECOUTATTEMPTCAUSE = 5 and SRVCCTYPE != 0 and TRIGGERQUANTITY = 0 and (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
Update EVENT_4104 set pmHoSigExeOutTimeS1Samp = 1 from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0;
Update EVENT_4104 set pmHoSigExeOutTimeS1Sum =
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) > 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
from EVENT_4104 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where PROCHOEXECOUTRESULT = 0;