
UPDATE EVENT_4122 SET pmErabModFailCause1 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 1 OR ERABMODIFYRESULT_1  = 1 OR ERABMODIFYRESULT_2  = 1 OR ERABMODIFYRESULT_3  = 1 OR ERABMODIFYRESULT_4  = 1 OR ERABMODIFYRESULT_5  = 1 OR ERABMODIFYRESULT_6  = 1 OR ERABMODIFYRESULT_7  = 1 OR ERABMODIFYRESULT_8  = 1 OR ERABMODIFYRESULT_9  = 1 OR ERABMODIFYRESULT_10 = 1 OR ERABMODIFYRESULT_11 = 1 OR ERABMODIFYRESULT_12 = 1 OR ERABMODIFYRESULT_13 = 1 OR ERABMODIFYRESULT_14 = 1 OR ERABMODIFYRESULT_15 = 1;


UPDATE EVENT_4122 SET pmErabModFailCause2 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID where
ERABMODIFYRESULT    = 2 OR ERABMODIFYRESULT_1  = 2 OR ERABMODIFYRESULT_2  = 2 OR ERABMODIFYRESULT_3  = 2 OR ERABMODIFYRESULT_4  = 2 OR ERABMODIFYRESULT_5  = 2 OR ERABMODIFYRESULT_6  = 2 OR ERABMODIFYRESULT_7  = 2 OR ERABMODIFYRESULT_8  = 2 OR ERABMODIFYRESULT_9  = 2 OR ERABMODIFYRESULT_10 = 2 OR ERABMODIFYRESULT_11 = 2 OR ERABMODIFYRESULT_12 = 2 OR ERABMODIFYRESULT_13 = 2 OR ERABMODIFYRESULT_14 = 2 OR ERABMODIFYRESULT_15 = 2;


UPDATE EVENT_4122 SET pmErabModFailCause3 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 3 OR ERABMODIFYRESULT_1  = 3 OR ERABMODIFYRESULT_2  = 3 OR ERABMODIFYRESULT_3  = 3 OR ERABMODIFYRESULT_4  = 3 OR ERABMODIFYRESULT_5  = 3 OR ERABMODIFYRESULT_6  = 3 OR ERABMODIFYRESULT_7  = 3 OR ERABMODIFYRESULT_8  = 3 OR ERABMODIFYRESULT_9  = 3 OR ERABMODIFYRESULT_10 = 3 OR ERABMODIFYRESULT_11 = 3 OR ERABMODIFYRESULT_12 = 3 OR ERABMODIFYRESULT_13 = 3 OR ERABMODIFYRESULT_14 = 3 OR ERABMODIFYRESULT_15 = 3;


UPDATE EVENT_4122 SET pmErabModFailCause4 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 4 OR ERABMODIFYRESULT_1  = 4 OR ERABMODIFYRESULT_2  = 4 OR ERABMODIFYRESULT_3  = 4 OR ERABMODIFYRESULT_4  = 4 OR ERABMODIFYRESULT_5  = 4 OR ERABMODIFYRESULT_6  = 4 OR ERABMODIFYRESULT_7  = 4 OR ERABMODIFYRESULT_8  = 4 OR ERABMODIFYRESULT_9  = 4 OR ERABMODIFYRESULT_10 = 4 OR ERABMODIFYRESULT_11 = 4 OR ERABMODIFYRESULT_12 = 4 OR ERABMODIFYRESULT_13 = 4 OR ERABMODIFYRESULT_14 = 4 OR ERABMODIFYRESULT_15 = 4;


UPDATE EVENT_4122 SET pmErabModFailCause5 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 5 OR ERABMODIFYRESULT_1  = 5 OR ERABMODIFYRESULT_2  = 5 OR ERABMODIFYRESULT_3  = 5 OR ERABMODIFYRESULT_4  = 5 OR ERABMODIFYRESULT_5  = 5 OR ERABMODIFYRESULT_6  = 5 OR ERABMODIFYRESULT_7  = 5 OR ERABMODIFYRESULT_8  = 5 OR ERABMODIFYRESULT_9  = 5 OR ERABMODIFYRESULT_10 = 5 OR ERABMODIFYRESULT_11 = 5 OR ERABMODIFYRESULT_12 = 5 OR ERABMODIFYRESULT_13 = 5 OR ERABMODIFYRESULT_14 = 5 OR ERABMODIFYRESULT_15 = 5;


UPDATE EVENT_4122 SET pmErabModFailCause6 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 6 OR ERABMODIFYRESULT_1  = 6 OR ERABMODIFYRESULT_2  = 6 OR ERABMODIFYRESULT_3  = 6 OR ERABMODIFYRESULT_4  = 6 OR ERABMODIFYRESULT_5  = 6 OR ERABMODIFYRESULT_6  = 6 OR ERABMODIFYRESULT_7  = 6 OR ERABMODIFYRESULT_8  = 6 OR ERABMODIFYRESULT_9  = 6 OR ERABMODIFYRESULT_10 = 6 OR ERABMODIFYRESULT_11 = 6 OR ERABMODIFYRESULT_12 = 6 OR ERABMODIFYRESULT_13 = 6 OR ERABMODIFYRESULT_14 = 6 OR ERABMODIFYRESULT_15 = 6;


UPDATE EVENT_4122 SET pmErabModFailCause7 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 7 OR ERABMODIFYRESULT_1  = 7 OR ERABMODIFYRESULT_2  = 7 OR ERABMODIFYRESULT_3  = 7 OR ERABMODIFYRESULT_4  = 7 OR ERABMODIFYRESULT_5  = 7 OR ERABMODIFYRESULT_6  = 7 OR ERABMODIFYRESULT_7  = 7 OR ERABMODIFYRESULT_8  = 7 OR ERABMODIFYRESULT_9  = 7 OR ERABMODIFYRESULT_10 = 7 OR ERABMODIFYRESULT_11 = 7 OR ERABMODIFYRESULT_12 = 7 OR ERABMODIFYRESULT_13 = 7 OR ERABMODIFYRESULT_14 = 7 OR ERABMODIFYRESULT_15 = 7;


UPDATE EVENT_4122 SET pmErabModFailCause8 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 8 OR ERABMODIFYRESULT_1  = 8 OR ERABMODIFYRESULT_2  = 8 OR ERABMODIFYRESULT_3  = 8 OR ERABMODIFYRESULT_4  = 8 OR ERABMODIFYRESULT_5  = 8 OR ERABMODIFYRESULT_6  = 8 OR ERABMODIFYRESULT_7  = 8 OR ERABMODIFYRESULT_8  = 8 OR ERABMODIFYRESULT_9  = 8 OR ERABMODIFYRESULT_10 = 8 OR ERABMODIFYRESULT_11 = 8 OR ERABMODIFYRESULT_12 = 8 OR ERABMODIFYRESULT_13 = 8 OR ERABMODIFYRESULT_14 = 8 OR ERABMODIFYRESULT_15 = 8;


UPDATE EVENT_4122 SET pmErabModFailCause9 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 9 OR ERABMODIFYRESULT_1  = 9 OR ERABMODIFYRESULT_2  = 9 OR ERABMODIFYRESULT_3  = 9 OR ERABMODIFYRESULT_4  = 9 OR ERABMODIFYRESULT_5  = 9 OR ERABMODIFYRESULT_6  = 9 OR ERABMODIFYRESULT_7  = 9 OR ERABMODIFYRESULT_8  = 9 OR ERABMODIFYRESULT_9  = 9 OR ERABMODIFYRESULT_10 = 9 OR ERABMODIFYRESULT_11 = 9 OR ERABMODIFYRESULT_12 = 9 OR ERABMODIFYRESULT_13 = 9 OR ERABMODIFYRESULT_14 = 9 OR ERABMODIFYRESULT_15 = 9;


UPDATE EVENT_4122 SET pmErabModFailCause10 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 10 OR ERABMODIFYRESULT_1  = 10 OR ERABMODIFYRESULT_2  = 10 OR ERABMODIFYRESULT_3  = 10 OR ERABMODIFYRESULT_4  = 10 OR ERABMODIFYRESULT_5  = 10 OR ERABMODIFYRESULT_6  = 10 OR ERABMODIFYRESULT_7  = 10 OR ERABMODIFYRESULT_8  = 10 OR ERABMODIFYRESULT_9  = 10 OR ERABMODIFYRESULT_10 = 10 OR ERABMODIFYRESULT_11 = 10 OR ERABMODIFYRESULT_12 = 10 OR ERABMODIFYRESULT_13 = 10 OR ERABMODIFYRESULT_14 = 10 OR ERABMODIFYRESULT_15 = 10;


UPDATE EVENT_4122 SET pmErabModFailCause11 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 11 OR ERABMODIFYRESULT_1  = 11 OR ERABMODIFYRESULT_2  = 11 OR ERABMODIFYRESULT_3  = 11 OR ERABMODIFYRESULT_4  = 11 OR ERABMODIFYRESULT_5  = 11 OR ERABMODIFYRESULT_6  = 11 OR ERABMODIFYRESULT_7  = 11 OR ERABMODIFYRESULT_8  = 11 OR ERABMODIFYRESULT_9  = 11 OR ERABMODIFYRESULT_10 = 11 OR ERABMODIFYRESULT_11 = 11 OR ERABMODIFYRESULT_12 = 11 OR ERABMODIFYRESULT_13 = 11 OR ERABMODIFYRESULT_14 = 11 OR ERABMODIFYRESULT_15 = 11;


UPDATE EVENT_4122 SET pmErabModFailCause12 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 12 OR ERABMODIFYRESULT_1  = 12 OR ERABMODIFYRESULT_2  = 12 OR ERABMODIFYRESULT_3  = 12 OR ERABMODIFYRESULT_4  = 12 OR ERABMODIFYRESULT_5  = 12 OR ERABMODIFYRESULT_6  = 12 OR ERABMODIFYRESULT_7  = 12 OR ERABMODIFYRESULT_8  = 12 OR ERABMODIFYRESULT_9  = 12 OR ERABMODIFYRESULT_10 = 12 OR ERABMODIFYRESULT_11 = 12 OR ERABMODIFYRESULT_12 = 12 OR ERABMODIFYRESULT_13 = 12 OR ERABMODIFYRESULT_14 = 12 OR ERABMODIFYRESULT_15 = 12;


UPDATE EVENT_4122 SET pmErabModFailCause13 = 
 (CASE WHEN ERABMODIFYRESULT    !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_1  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_2  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_3  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_4  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_5  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_6  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_7  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_8  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_9  !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_10 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_11 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_12 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_13 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_14 !=0  THEN 1 ELSE 0 END) +
 (CASE WHEN ERABMODIFYRESULT_15 !=0  THEN 1 ELSE 0 END) 
from EVENT_4122 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE 
ERABMODIFYRESULT    = 13 OR ERABMODIFYRESULT_1  = 13 OR ERABMODIFYRESULT_2  = 13 OR ERABMODIFYRESULT_3  = 13 OR ERABMODIFYRESULT_4  = 13 OR ERABMODIFYRESULT_5  = 13 OR ERABMODIFYRESULT_6  = 13 OR ERABMODIFYRESULT_7  = 13 OR ERABMODIFYRESULT_8  = 13 OR ERABMODIFYRESULT_9  = 13 OR ERABMODIFYRESULT_10 = 13 OR ERABMODIFYRESULT_11 = 13 OR ERABMODIFYRESULT_12 = 13 OR ERABMODIFYRESULT_13 = 13 OR ERABMODIFYRESULT_14 = 13 OR ERABMODIFYRESULT_15 = 13;
