Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause0  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=0;
Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause1  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=1;
Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause2  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=2;
Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause3  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=3;
Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause4  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=4;
Update EVENT_5208 set pmS1NasNonDelivIndMiscS1Cause5  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 4 and a3GPPCAUSE=5;
Update EVENT_5208 set pmS1NasNonDelivIndNasS1Cause0  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 2 and a3GPPCAUSE=0;
Update EVENT_5208 set pmS1NasNonDelivIndNasS1Cause1  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 2 and a3GPPCAUSE=1;
Update EVENT_5208 set pmS1NasNonDelivIndNasS1Cause2  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID  WHERE a3GPPCAUSEGROUP = 2 and a3GPPCAUSE=2;
Update EVENT_5208 set pmS1NasNonDelivIndNasS1Cause3  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 2 and a3GPPCAUSE=3;
Update EVENT_5208 set pmS1NasNonDelivIndNasS1Cause4  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 2 and a3GPPCAUSE=4;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause0  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=0;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause1  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=1;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause2  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=2;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause3  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=3;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause4  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=4;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause5  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=5;
Update EVENT_5208 set pmS1NasNonDelivIndProtS1Cause6  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 3 and a3GPPCAUSE=6;   
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause0   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=0 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause1   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=1 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause2   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=2 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause3   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=3 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause4   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=4 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause5   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=5 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause6   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=6 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause7   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=7 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause8   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=8 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause9   =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=9 ;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause10  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=10;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause11  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=11;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause12  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=12;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause13  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=13;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause14  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=14;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause15  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=15;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause16  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=16;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause17  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=17;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause18  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=18;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause19  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=19;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause20  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=20;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause21  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=21;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause22  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=22;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause23  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=23;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause24  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=24;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause25  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=25;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause26  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=26;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause27  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=27;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause28  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=28;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause29  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=29;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause30  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=30;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause31  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=31;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause32  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=32;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause33  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=33;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause34  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID  WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=34;
Update EVENT_5208 set pmS1NasNonDelivIndRnlS1Cause35  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 0 and a3GPPCAUSE=35;
Update EVENT_5208 set pmS1NasNonDelivIndTranS1Cause0  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 1 and a3GPPCAUSE=0;
Update EVENT_5208 set pmS1NasNonDelivIndTranS1Cause1  =  1 from EVENT_5208 A inner join topo_eucell B on A.CELL_ID = B.CELL_ID and A.ENB_ID = B.ENB_ID WHERE a3GPPCAUSEGROUP = 1 and a3GPPCAUSE=1;