Alter Table EVENT3_4102 add CELLRELATIONMOID as varchar null;
//CELL_TYPE EUTRAN
Update EVENT3_4102
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4102 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4102.CELL_ID 
AND TOPO_CELLRELATION.NBR_ENB_ID=EVENT3_4102.NBR_ENB_ID 
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4102.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4102.ENB_ID ;
//CELL_TYPE UTRAN
Update EVENT3_4102
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4102 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4102.CELL_ID 
AND TOPO_CELLRELATION.NBR_RNC_ID=EVENT3_4102.NBR_RNC_ID 
AND TOPO_CELLRELATION.NBR_MCC=EVENT3_4102.NBR_MCC_ID 
AND TOPO_CELLRELATION.NBR_MNC=EVENT3_4102.NBR_MNC_ID
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4102.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4102.ENB_ID ;