Alter Table EVENT3_4104 add CELLRELATIONMOID as varchar null;
Update EVENT3_4104
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4104 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4104.CELL_ID 
AND TOPO_CELLRELATION.NBR_ENB_ID=EVENT3_4104.NBR_ENB_ID 
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4104.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4104.ENB_ID ;
//CELL_TYPE UTRAN
Update EVENT3_4104
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4104 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4104.CELL_ID 
AND TOPO_CELLRELATION.NBR_RNC_ID=EVENT3_4104.NBR_RNC_ID 
AND TOPO_CELLRELATION.NBR_MCC=EVENT3_4104.NBR_MCC_ID 
AND TOPO_CELLRELATION.NBR_MNC=EVENT3_4104.NBR_MNC_ID
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4104.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4104.ENB_ID ;
//CELL_TYPE GERAN
Update EVENT3_4104
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4104 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4104.CELL_ID 
AND TOPO_CELLRELATION.NBR_LAC_ID=EVENT3_4104.NBR_LAC_ID 
AND TOPO_CELLRELATION.NBR_MCC=EVENT3_4104.NBR_MCC_ID 
AND TOPO_CELLRELATION.NBR_MNC=EVENT3_4104.NBR_MNC_ID
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4104.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4104.ENB_ID ;