Alter Table EVENT3_4110 add CELLRELATIONMOID as varchar null;
//CELL_TYPE EUTRAN
Update EVENT3_4110
set CELLRELATIONMOID =TOPO_CELLRELATION.MOID from TOPO_CELLRELATION INNER JOIN EVENT3_4110 
ON TOPO_CELLRELATION.CELl_ID=EVENT3_4110.CELL_ID 
AND TOPO_CELLRELATION.NBR_ENB_ID=EVENT3_4110.NBR_ENB_ID 
AND TOPO_CELLRELATION.NBR_CELL_ID=EVENT3_4110.NBR_CELL_ID
AND TOPO_CELLRELATION.ENB_ID = EVENT3_4110.ENB_ID ;