Update EVENT3_4123 set pmX2ConnResetInMiscX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetInMiscX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=1;
	
Update EVENT3_4123 set pmX2ConnResetInMiscX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=2;
	
Update EVENT3_4123 set pmX2ConnResetInMiscX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=3;
	
Update EVENT3_4123 set pmX2ConnResetInMiscX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=4;






Update EVENT3_4123 set pmX2ConnResetInProtX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=1;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=2;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=3;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=4;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause5 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=5;
	
Update EVENT3_4123 set pmX2ConnResetInProtX2Cause6 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=6;


Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=1;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=2;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=3;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=4;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause5 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=5;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause6 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=6;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause7 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=7;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause8 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=8;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause9 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=9;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause10 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=10;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause11 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=11;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause12 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=12;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause13 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=13;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause14 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=14;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause15 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=15;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause16 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=16;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause17 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=17;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause18 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=18;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause19 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=19;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause20 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=20;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause21 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=21;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause22 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=22;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause23 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=23;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause24 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=24;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause25 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=25;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause26 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=26;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause27 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=27;
	
Update EVENT3_4123 set pmX2ConnResetInRnlX2Cause28 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=28;


Update EVENT3_4123 set pmX2ConnResetInTranX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 1 AND a3GPPCAUSE=0 ;
	
Update EVENT3_4123 set pmX2ConnResetInTranX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=0  AND a3GPPCAUSEGROUP = 1 AND a3GPPCAUSE=1;


Update EVENT3_4123 set pmX2ConnResetOutMiscX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutMiscX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=1;
	
Update EVENT3_4123 set pmX2ConnResetOutMiscX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=2;
	
Update EVENT3_4123 set pmX2ConnResetOutMiscX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=3;
	
Update EVENT3_4123 set pmX2ConnResetOutMiscX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 4 AND a3GPPCAUSE=4;





Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0 ;
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1 AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0 ;
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0 ; 
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause5 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutProtX2Cause6 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 3 AND a3GPPCAUSE=0;


Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=1;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause2 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=2;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause3 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=3;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause4 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=4;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause5 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=5; 
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause6 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=6;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause7 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=7;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause8 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=8;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause9 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=9;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause10 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=10 ;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause11 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=11;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause12 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=12; 
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause13 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=13;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause14 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=14;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause15 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=15;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause16 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=16;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause17 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=17;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause18 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=18;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause19 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=19;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause20 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=20;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause21 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=21;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause22 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=22;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause23 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=23;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause24 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=24;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause25 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=25;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause26 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=26;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause27 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=27;
	
Update EVENT3_4123 set pmX2ConnResetOutRnlX2Cause28 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 0 AND a3GPPCAUSE=28;




Update EVENT3_4123 set pmX2ConnResetOutTranX2Cause0 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 1 AND a3GPPCAUSE=0;
	
Update EVENT3_4123 set pmX2ConnResetOutTranX2Cause1 = 1 from EVENT3_4123 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where  MESSAGEDIRECTION=1  AND a3GPPCAUSEGROUP = 1 AND a3GPPCAUSE=1;