

Update EVENT3_4124 set pmS1ConnShutdownTimeDistr=1 from EVENT3_4124 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where SCTPENDPOINTTYPE=0;

Update EVENT3_4124 set pmS1ConnShutdownTimeSamp=1 from EVENT3_4124 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID where SCTPENDPOINTTYPE=0;

Update EVENT3_4124 set pmS1ConnShutdownTimeSum = 
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) >= 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
) from EVENT3_4124 A 
inner
  join TOPO_ENBFUNCTION B
    on A.ENB_ID = B.ENB_ID
 where SCTPENDPOINTTYPE=0;