ALTER TABLE EVENT16A16A_3117
ADD pmPrbUlUtilDistrPartition1 as INT NULL,
ADD pmPrbUlUtilDistrPartition2 as INT NULL,
ADD pmPrbUlUtilDistrPartition3 as INT NULL,
ADD pmPrbUlUtilDistrPartition4 as INT NULL,
ADD pmPrbUlUtilDistrPartition5 as INT NULL,
ADD pmPrbUlUtilDistrPartition6 as INT NULL,
ADD pmPrbUlUtilDistrPartition7 as INT NULL,
ADD pmPrbUlUtilDistrPartition8 as INT NULL,
ADD pmPrbUlUtilDistrPartition9 as INT NULL,
ADD pmPrbUlUtilDistrPartition10 as INT NULL,
ADD pmPrbUlUtilDistrPartition11 as INT NULL,
ADD pmPrbUlUtilDistrPartition12 as INT NULL,
ADD pmPrbUlUtilDistrPartition13 as INT NULL,
ADD pmPrbUlUtilDistrPartition14 as INT NULL,
ADD pmPrbUlUtilDistrPartition15 as INT NULL,
ADD pmPrbUlUtilDistrPartition16 as INT NULL,
ADD pmPrbUlUtilDistrPartition17 as INT NULL,
ADD pmPrbUlUtilDistrPartition18 as INT NULL,
ADD pmPrbUlUtilDistrPartition19 as INT NULL,
ADD pmPrbUlUtilDistrPartition20 as INT NULL,
ADD pmPrbUlUtilDistrPartition21 as INT NULL,
ADD pmPrbUlUtilDistrPartition22 as INT NULL,
ADD pmPrbUlUtilDistrPartition23 as INT NULL,
ADD pmPrbUlUtilDistrPartition24 as INT NULL;

ALTER TABLE EVENT16A16A17A_3117
 ADD pmPrbDlUtilDistrPartition1 as INT NULL,
 ADD pmPrbDlUtilDistrPartition2 as INT NULL,
 ADD pmPrbDlUtilDistrPartition3 as INT NULL,
 ADD pmPrbDlUtilDistrPartition4 as INT NULL,
 ADD pmPrbDlUtilDistrPartition5 as INT NULL,
 ADD pmPrbDlUtilDistrPartition6 as INT NULL,
 ADD pmPrbDlUtilDistrPartition7 as INT NULL,
 ADD pmPrbDlUtilDistrPartition8 as INT NULL,
 ADD pmPrbDlUtilDistrPartition9 as INT NULL,
 ADD pmPrbDlUtilDistrPartition10 as INT NULL,
 ADD pmPrbDlUtilDistrPartition11 as INT NULL,
 ADD pmPrbDlUtilDistrPartition12 as INT NULL,
 ADD pmPrbDlUtilDistrPartition13 as INT NULL,
 ADD pmPrbDlUtilDistrPartition14 as INT NULL,
 ADD pmPrbDlUtilDistrPartition15 as INT NULL,
 ADD pmPrbDlUtilDistrPartition16 as INT NULL,
 ADD pmPrbDlUtilDistrPartition17 as INT NULL,
 ADD pmPrbDlUtilDistrPartition18 as INT NULL,
 ADD pmPrbDlUtilDistrPartition19 as INT NULL,
 ADD pmPrbDlUtilDistrPartition20 as INT NULL,
 ADD pmPrbDlUtilDistrPartition21 as INT NULL,
 ADD pmPrbDlUtilDistrPartition22 as INT NULL,
 ADD pmPrbDlUtilDistrPartition23 as INT NULL,
 ADD pmPrbDlUtilDistrPartition24 as INT NULL;
 
ALTER TABLE EVENT16A16A17A_3117
ADD pmCceUtilDistrPartition1 as INT NULL,
ADD pmCceUtilDistrPartition2 as INT NULL,
ADD pmCceUtilDistrPartition3 as INT NULL,
ADD pmCceUtilDistrPartition4 as INT NULL,
ADD pmCceUtilDistrPartition5 as INT NULL,
ADD pmCceUtilDistrPartition6 as INT NULL,
ADD pmCceUtilDistrPartition7 as INT NULL,
ADD pmCceUtilDistrPartition8 as INT NULL,
ADD pmCceUtilDistrPartition9 as INT NULL,
ADD pmCceUtilDistrPartition10 as INT NULL,
ADD pmCceUtilDistrPartition11 as INT NULL,
ADD pmCceUtilDistrPartition12 as INT NULL,
ADD pmCceUtilDistrPartition13 as INT NULL,
ADD pmCceUtilDistrPartition14 as INT NULL,
ADD pmCceUtilDistrPartition15 as INT NULL,
ADD pmCceUtilDistrPartition16 as INT NULL,
ADD pmCceUtilDistrPartition17 as INT NULL,
ADD pmCceUtilDistrPartition18 as INT NULL,
ADD pmCceUtilDistrPartition19 as INT NULL,
ADD pmCceUtilDistrPartition20 as INT NULL,
ADD pmCceUtilDistrPartition21 as INT NULL,
ADD pmCceUtilDistrPartition22 as INT NULL,
ADD pmCceUtilDistrPartition23 as INT NULL,
ADD pmCceUtilDistrPartition24 as INT NULL;



