ALTER TABLE EVENT3_4102
ADD pmHoPrepOutRejTdScdmaRnlS1Cause15 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause16 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause17 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause18 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause19 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause20 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause21 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause22 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause23 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause24 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause25 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause26 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause27 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause28 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause29 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause30 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause31 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause32 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause33 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause34 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause35 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause36 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause37 as int null ,
ADD pmHoPrepOutRejTdScdmaRnlS1Cause38 as int null ;
ALTER TABLE EVENT3_4102 ADD pmHoPrepOutRejTdScdmaTranS1Cause0 as int null,
ADD pmHoPrepOutRejTdScdmaTranS1Cause1 as int null ;
Alter Table EVENT3_4102 add pmHoPrepOutS1AttInterEnb as int null;
ALTER TABLE EVENT3_4102 ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause0 as int null,
ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause1 as int null ,
ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause2 as int null ,
ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause3 as int null ,
ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause4 as int null ,
ADD pmHoPrepOutS1RejInterEnbInterFreqMiscS1Cause5 as int null ;
ALTER TABLE EVENT3_4102 ADD pmHoPrepOutS1RejInterEnbInterFreqNasS1Cause0 as int null,
ADD pmHoPrepOutS1RejInterEnbInterFreqNasS1Cause1 as int null,
ADD pmHoPrepOutS1RejInterEnbInterFreqNasS1Cause2 as int null,
ADD pmHoPrepOutS1RejInterEnbInterFreqNasS1Cause3 as int null,
ADD pmHoPrepOutS1RejInterEnbInterFreqNasS1Cause4 as int null ;