ALTER TABLE EVENT3_4110 ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause20 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause21 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause22 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause23 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause24 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause25 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause26 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause27 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqRnlX2Cause28 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqTranX2Cause0 as int null,
ADD pmHoPrepOutRejIntraEnbInterFreqTranX2Cause1 as int null,
ADD pmHoPrepOutRejIntraEnbIntraFreqTranX2Cause0 as int null,
ADD pmHoPrepOutRejIntraEnbIntraFreqTranX2Cause1 as int null,
ADD pmHoPrepOutX2AttInterEnb as int null ;
ALTER TABLE EVENT3_4110 ADD pmHoPrepOutX2SuccInterEnb as int null;