/*TOPO_CELLRELATION EUTRAN */
UPDATE EVENT_4110 SET ENB_ID = (GLOBALCELLID / 256) WHERE (HOSOURCEORTARGETTYPE=0  OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4110 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE (HOSOURCEORTARGETTYPE=0  OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4110 SET NBR_ENB_ID =  (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *4096) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xFF)*16) + ( ((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =0 OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4110 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,13,2)))  & 0x0F)*16) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =0 OR HOSOURCEORTARGETTYPE =1);
/* TOPO_CELLRELATION UTRAN */
UPDATE EVENT_4110 SET ENB_ID = (GLOBALCELLID / 256) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4110 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4110 SET NBR_RNC_ID = (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *16) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xF0)/16) where  (HOSOURCEORTARGETTYPE=2 OR HOSOURCEORTARGETTYPE=5);
UPDATE EVENT_4110 SET NBR_MCC_ID = substring(NEIGHBORCGI, 4, 1) | substring(NEIGHBORCGI, 3, 1) | substring(NEIGHBORCGI, 6, 1) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4110 SET NBR_MNC_ID =(CASE WHEN substring(NEIGHBORCGI, 5, 1) = 'f' THEN (substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) ELSE (substring(NEIGHBORCGI, 5, 1) + substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) END) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4110 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,11,2)))  & 0x0F)*4096)+(((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xFF)*16) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5); 
/* TOPO_CELLRELATION GERAN */
UPDATE EVENT_4110 SET ENB_ID = (GLOBALCELLID / 256) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4110 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4110 SET NBR_LAC_ID = (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *256) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xFF)) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4110 SET NBR_MCC_ID = substring(NEIGHBORCGI, 4, 1) | substring(NEIGHBORCGI, 3, 1) | substring(NEIGHBORCGI, 6, 1) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4110 SET NBR_MNC_ID =(CASE WHEN substring(NEIGHBORCGI, 5, 1) = 'f' THEN (substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) ELSE (substring(NEIGHBORCGI, 5, 1) + substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) END) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4110 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xFF)*256) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xFF)) WHERE HOSOURCEORTARGETTYPE =3;
/* TOPO_CELLRELATION EUTRAN */
UPDATE EVENT_4102 SET ENB_ID = (GLOBALCELLID / 256) WHERE (HOSOURCEORTARGETTYPE=0  OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4102 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE (HOSOURCEORTARGETTYPE=0  OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4102 SET NBR_ENB_ID =  (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *4096) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xFF)*16) + ( ((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =0 OR HOSOURCEORTARGETTYPE =1);
UPDATE EVENT_4102 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,13,2)))  & 0x0F)*16) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =0 OR HOSOURCEORTARGETTYPE =1);
/* TOPO_CELLRELATION UTRAN */
UPDATE EVENT_4102 SET ENB_ID = (GLOBALCELLID / 256) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4102 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4102 SET NBR_RNC_ID = (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *16) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xF0)/16) where  (HOSOURCEORTARGETTYPE=2 OR HOSOURCEORTARGETTYPE=5);
UPDATE EVENT_4102 SET NBR_MCC_ID = substring(NEIGHBORCGI, 4, 1) | substring(NEIGHBORCGI, 3, 1) | substring(NEIGHBORCGI, 6, 1) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4102 SET NBR_MNC_ID =(CASE WHEN substring(NEIGHBORCGI, 5, 1) = 'f' THEN (substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) ELSE (substring(NEIGHBORCGI, 5, 1) + substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) END) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5);
UPDATE EVENT_4102 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,11,2)))  & 0x0F)*4096)+(((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xFF)*16) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xF0)/16) WHERE (HOSOURCEORTARGETTYPE =2 OR HOSOURCEORTARGETTYPE =5); 
/* TOPO_CELLRELATION GERAN */
UPDATE EVENT_4102 SET ENB_ID = (GLOBALCELLID / 256) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4102 SET CELL_ID = (GLOBALCELLID - (GLOBALCELLID / 256)*256) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4102 SET NBR_LAC_ID = (((hextoint(substring(NEIGHBORCGI,9,2))) & 0xFF) *256) + ( ((hextoint(substring(NEIGHBORCGI,11,2)))  & 0xFF)) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4102 SET NBR_MCC_ID = substring(NEIGHBORCGI, 4, 1) | substring(NEIGHBORCGI, 3, 1) | substring(NEIGHBORCGI, 6, 1) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4102 SET NBR_MNC_ID =(CASE WHEN substring(NEIGHBORCGI, 5, 1) = 'f' THEN (substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) ELSE (substring(NEIGHBORCGI, 5, 1) + substring(NEIGHBORCGI, 8, 1) + substring(NEIGHBORCGI, 7, 1)) END) WHERE HOSOURCEORTARGETTYPE =3;
UPDATE EVENT_4102 SET NBR_CELL_ID = (((hextoint(substring(NEIGHBORCGI,13,2)))  & 0xFF)*256) + ( ((hextoint(substring(NEIGHBORCGI,15,2)))  & 0xFF)) WHERE HOSOURCEORTARGETTYPE =3;