ALTER TABLE Input_1025 ADD ENB_ID as int null;
ALTER TABLE Input_1067 ADD ENB_ID as int null;
ALTER TABLE Input_1091 ADD ENB_ID as int null;
ALTER TABLE Input_29 ADD ENB_ID as int null;
ALTER TABLE Input_30 ADD ENB_ID as int null;
ALTER TABLE Input_3084 ADD ENB_ID AS int null;
ALTER TABLE Input_3107 ADD ENB_ID as int null;
ALTER TABLE Input_3108 ADD ENB_ID as int null;
ALTER TABLE Input_3117 ADD ENB_ID as int null;
ALTER TABLE Input_32 ADD ENB_ID as int null;
ALTER TABLE Input_35 ADD ENB_ID as int null;
ALTER TABLE Input_4097 ADD ENB_ID as int null;
ALTER TABLE Input_4099 ADD ENB_ID as int null;
ALTER TABLE Input_4102 ADD ENB_ID AS int null;
ALTER TABLE Input_4103 ADD ENB_ID as int null;
ALTER TABLE Input_4104 ADD ENB_ID as int null;
ALTER TABLE Input_4105 ADD ENB_ID as int null;
ALTER TABLE Input_4106 ADD ENB_ID as int null;
ALTER TABLE Input_4110 ADD ENB_ID as int null;
ALTER TABLE Input_4111 ADD ENB_ID as int null;
ALTER TABLE Input_4112 ADD ENB_ID as int null;
ALTER TABLE Input_4113 ADD ENB_ID as int null;
ALTER TABLE Input_4114 ADD ENB_ID as int null;
ALTER TABLE Input_4116 ADD ENB_ID AS int null;
ALTER TABLE Input_4117 ADD ENB_ID as int null;
ALTER TABLE Input_4118 ADD ENB_ID AS int null;
ALTER TABLE Input_4120 ADD ENB_ID as int null;
ALTER TABLE Input_4121 ADD ENB_ID as int null;
ALTER TABLE Input_4122 ADD ENB_ID as int null;
ALTER TABLE Input_4123 ADD ENB_ID AS int null ;
ALTER TABLE Input_4124 ADD ENB_ID AS int null ;
ALTER TABLE Input_4125 ADD ENB_ID as int null;
ALTER TABLE Input_4126 ADD ENB_ID as int null;
ALTER TABLE Input_4134 ADD ENB_ID as int null;
ALTER TABLE Input_4138 ADD ENB_ID as int null;
ALTER TABLE Input_4139 ADD ENB_ID as int null;
ALTER TABLE Input_5146 ADD ENB_ID as int null;
ALTER TABLE Input_5147 ADD ENB_ID as int null;
ALTER TABLE Input_5173 ADD ENB_ID as int null;
ALTER TABLE Input_5208 ADD ENB_ID as int null;
ALTER TABLE Input_5209 ADD ENB_ID AS int null ;
ALTER TABLE Input_5210 ADD ENB_ID AS int null ;
ALTER TABLE Input_5221 ADD ENB_ID as int null;
ALTER TABLE Input_5222 ADD ENB_ID as int null;
ALTER TABLE Input_5223 ADD ENB_ID as int null;
ALTER TABLE Input_5224 ADD ENB_ID as int null;
ALTER TABLE Input_5228 ADD ENB_ID as int null;
ALTER TABLE Input_5229 ADD ENB_ID as int null;
ALTER TABLE Input_5230 ADD ENB_ID as int null;
ALTER TABLE Input_5262 ADD ENB_ID as int null;

