Alter Table EVENT3_4116 add MOID as int  null;

Update EVENT3_4116
set MOID =TOPO_TERMPOINTTOMME.MOID from TOPO_TERMPOINTTOMME INNER JOIN EVENT3_4116 ON 
TOPO_TERMPOINTTOMME.MME_CODE=EVENT3_4116.MME_CODE AND 
TOPO_TERMPOINTTOMME.MME_GROUP_ID=EVENT3_4116.MME_GROUP_ID AND TOPO_TERMPOINTTOMME.MCC=EVENT3_4116.MCC 
AND TOPO_TERMPOINTTOMME.MNC=EVENT3_4116.MNC
AND TOPO_TERMPOINTTOMME.ENB_ID=EVENT3_4116.ENB_ID;
