Update EVENT_4112 set pmHoSigExeOutTimeX2Samp=1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where  HOTYPE=2 AND PROCHOEXECOUTRESULT=0 ;

Update EVENT_4112 set pmHoSigExeOutTimeX2Sum =
(
case when MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) > 0 
then 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000) 
else 
MOD(
((TIMESTAMPSTOPHOUR-TIMESTAMPSTARTHOUR)*3600000) +
((TIMESTAMPSTOPMINUTE-TIMESTAMPSTARTMINUTE)*60000) + 
((TIMESTAMPSTOPSECOND-TIMESTAMPSTARTSECOND)*1000) 
+(TIMESTAMPSTOPMILLISEC-TIMESTAMPSTARTMILLISEC)
,3600000)+3600000 end
)
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where HOTYPE=2 AND PROCHOEXECOUTRESULT = 0;

Update EVENT_4112 set pmHoExeAttLteInterFUeMeas = 1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where HOSOURCEORTARGETTYPE = 1 and (PROCHOEXECOUTATTEMPTCAUSE = 1 or PROCHOEXECOUTRESULT = 3);

Update EVENT_4112 set pmHoExeAttLteInterFUeMeasRsrp = 1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where HOSOURCEORTARGETTYPE = 1 and TRIGGERQUANTITY = 0 and (PROCHOEXECOUTATTEMPTCAUSE = 1 or PROCHOEXECOUTATTEMPTCAUSE = 3);

Update EVENT_4112 set pmHoExeSuccLteInterFUeMeas = 1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where (PROCHOEXECOUTRESULT = 0 and 
HOSOURCEORTARGETTYPE = 1 and (PROCHOEXECOUTATTEMPTCAUSE = 1 or PROCHOEXECOUTATTEMPTCAUSE = 3)) ;

Update EVENT_4112 set pmHoExeSuccLteInterFUeMeasRsrp = 1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where (PROCHOEXECOUTRESULT = 0 and 
HOSOURCEORTARGETTYPE = 1 and TRIGGERQUANTITY = 0 and (PROCHOEXECOUTATTEMPTCAUSE = 1 or PROCHOEXECOUTATTEMPTCAUSE = 3));

Update EVENT_4112 set pmHoExeSuccLteInterFAto=1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where PROCHOEXECOUTATTEMPTCAUSE=18 AND HOSOURCEORTARGETTYPE=1 AND PROCHOEXECOUTRESULT=0;


Update EVENT_4112 set pmHoExeAttLteInterFAto=1 
from EVENT_4112 A
inner
  join topo_cellrelation B
    on 	A.CELL_ID = B.CELL_ID and 
	A.ENB_ID = B.ENB_ID and
	A.NBR_ENB_ID = B.NBR_ENB_ID and
	A.NBR_CELL_ID = B.NBR_CELL_ID
where PROCHOEXECOUTATTEMPTCAUSE=18 AND HOSOURCEORTARGETTYPE=1; 